from yacs.config import CfgNode as CN

_C = CN()

_C.EPOCHS = 100
_C.LEARNING_RATE = 0.00045

# [Modified] 显存优化：Batch Size 降为 8，通过累积达到 32 的效果
_C.BATCH_SIZE = 8
_C.ACCUM_ITER = 4  # [New] 梯度累积步数：8 * 4 = 32

_C.WEIGHT_DECAY = 0.0001
_C.MOMENTUM = 0.9

_C.WORKERS = 8
_C.TIME_LIMIT = 86100

_C.SEED = 42
_C.USE_CUDA = True
_C.VERBOSE = True
_C.DROP_LAST = False
_C.DROP_OUT = 0.0
_C.LOG_STEP = 5
_C.VAL_EPOCH = 1
_C.OUT_DIR = "/datasets/work/hb-nhmrc-dhcp/work/liu275/DGDR/output_esdg_h100"

_C.RANDOM = False
_C.OVERRIDE = True

_C.ALGORITHM = "GDRNet"
_C.DG_MODE = "ESDG"
_C.BACKBONE = "FPT"

_C.MOCO_QUEUE_K = 1024
_C.MOCO_MOMENTUM = 0.999

_C.SMOOTH = 0.4
_C.KD = 0.1
_C.POSITIVE = 4
_C.P = 0.2
_C.MASKED = 0.5
_C.SUP = 0.0
_C.MIXUP = False
_C.FASTMOCO = 1.0

_C.MASK_RATIO = 0.5
_C.BLOCK_SIZE = 32

_C.GDRNET = CN()
_C.GDRNET.BETA = 0.1
_C.GDRNET.TEMPERATURE = 0.1
_C.GDRNET.SCALING_FACTOR = 4.0
_C.GDRNET.MASKED = 0.5

_C.GDRNET.LAMBDA_SUP = 1.0
_C.GDRNET.LAMBDA_MASKED = 1.0
_C.GDRNET.LAMBDA_SIAM = 0.0
_C.GDRNET.LAMBDA_DINO = 1.0

_C.GDRNET.SDCLR_ENABLE = True
_C.GDRNET.SDCLR_RATIO = 0.5
_C.GDRNET.LAMBDA_SDCLR = 0.5

_C.DATASET = CN()
_C.DATASET.NAME = "GDRBench"
_C.DATASET.NUM_CLASSES = 5
_C.DATASET.ROOT = "/datasets/work/hb-nhmrc-dhcp/work/liu275/DGDR/GDR_Formatted_Data"
_C.DATASET.IMBALANCE = False

_C.DATASET.SOURCE_DOMAINS = ("MESSIDOR",)
_C.DATASET.TARGET_DOMAINS = ("APTOS", "DDR", "DEEPDR", "EYEPACS", "FGADR", "IDRID", "RLDR")

_C.INPUT = CN()
_C.INPUT.SIZE = 512

_C.MODEL = CN()
_C.MODEL.NAME = ""

_C.MODEL.FPT = CN()
_C.MODEL.FPT.SELECTION_RATIO = 0.5
_C.MODEL.FPT.LPM_PATH = "/datasets/work/hb-nhmrc-dhcp/work/liu275/DGDR/checkpoints/dinov3_vitb16"
_C.MODEL.FPT.SIDE_PRETRAINED_PATH = "/datasets/work/hb-nhmrc-dhcp/work/liu275/DGDR/checkpoints/resnet50-19c8e357.pth"
_C.MODEL.FPT.HIGH_RES_SIZE = 512
_C.MODEL.FPT.LOW_RES_SIZE = 224
_C.MODEL.FPT.SIDE_LAYERS = 12
_C.MODEL.FPT.LAYERS_TO_EXTRACT = [0, 3, 6, 9]

_C.OPTIM = CN()
_C.OPTIM.NAME = ""

_C.TRANSFORM = CN()
_C.TRANSFORM.NAME = []
_C.TRANSFORM.AUGPROB = 0.5
_C.TRANSFORM.FREQ = False
_C.TRANSFORM.TEST_FREQ = False
_C.TRANSFORM.R = 0.0

_C.TRANSFORM.COLORJITTER_B = 1.0
_C.TRANSFORM.COLORJITTER_C = 1.0
_C.TRANSFORM.COLORJITTER_S = 1.0
_C.TRANSFORM.COLORJITTER_H = 0.05