from yacs.config import CfgNode as CN

_C = CN()
_C.OUT_DIR = "./output"
_C.SEED = 42
_C.USE_CUDA = True
_C.VERBOSE = True
_C.DROP_LAST = True
_C.DROP_OUT = 0.0
_C.LOG_STEP = 5

_C.EPOCHS = 100
_C.LEARNING_RATE = 0.01
_C.BATCH_SIZE = 16
_C.WEIGHT_DECAY = 1e-4
_C.MOMENTUM = 0.9

# --- Mask-Siam ---
_C.MASK_RATIO = 0.75
_C.BLOCK = 32
_C.FASTMOCO = 0.5
_C.SIAM_LAMBDA = 0.1
_C.POSITIVE = 4
_C.KD = 0.1

_C.ALGORITHM = "GDRNet_MASK_SIAM"
_C.BACKBONE = "resnet50"
_C.VAL_EPOCH = 1

_C.TRANSFORM = CN()
_C.TRANSFORM.AUGPROB = 0.5
_C.TRANSFORM.COLORJITTER_B = 1
_C.TRANSFORM.COLORJITTER_C = 1
_C.TRANSFORM.COLORJITTER_S = 1
_C.TRANSFORM.COLORJITTER_H = 0.05

_C.DATASET = CN()
_C.DATASET.ROOT = ""
_C.DATASET.NUM_CLASSES = 5
_C.DATASET.SOURCE_DOMAINS = ()
_C.DATASET.TARGET_DOMAINS = ()

_C.GDRNET = CN()
_C.GDRNET.BETA = 0.5
_C.GDRNET.TEMPERATURE = 0.1
_C.GDRNET.SCALING_FACTOR = 4.