from yacs.config import CfgNode as CN

_C = CN()

_C.EPOCHS = 100
_C.LEARNING_RATE = 1e-3
_C.BATCH_SIZE = 16
_C.WEIGHT_DECAY = 5e-4
_C.MOMENTUM = 0.9

_C.INPUT = CN()
_C.INPUT.SIZE = 512

_C.MODEL = CN()
_C.MODEL.NAME = ""

_C.MODEL.FPT = CN()
_C.MODEL.FPT.SELECTION_RATIO = 0.2
_C.MODEL.FPT.LPM_PATH = "/datasets/work/hb-nhmrc-dhcp/work/liu275/DGDR/checkpoints/dinov3_vitb16"
_C.MODEL.FPT.HIGH_RES_SIZE = 512
_C.MODEL.FPT.LOW_RES_SIZE = 224
_C.MODEL.FPT.SIDE_LAYERS = 12
_C.MODEL.FPT.LAYERS_TO_EXTRACT = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

_C.OUT_DIR = "./output"
_C.SEED = 42
_C.USE_CUDA = True
_C.VERBOSE = True
_C.DROP_LAST = False
_C.DROP_OUT = 0.0
_C.LOG_STEP = 5

_C.ALGORITHM = "GDRNet"
_C.BACKBONE = "resnet50"
_C.RANDOM = False
_C.OVERRIDE = True
_C.VAL_EPOCH = 1

_C.OPTIM = CN()
_C.OPTIM.NAME = ""

_C.TRANSFORM = CN()
_C.TRANSFORM.NAME = []
_C.TRANSFORM.AUGPROB = 0.5

_C.TRANSFORM.COLORJITTER_B = 1
_C.TRANSFORM.COLORJITTER_C = 1
_C.TRANSFORM.COLORJITTER_S = 1
_C.TRANSFORM.COLORJITTER_H = 0.05

_C.DATASET = CN()
_C.DATASET.NAME = "GDRBench"
_C.DATASET.ROOT = ""
_C.DATASET.NUM_CLASSES = 5
_C.DATASET.SOURCE_DOMAINS = ()
_C.DATASET.TARGET_DOMAINS = ()

# --- [SPMix Archive] ---
# _C.DATASET.SPMIX_PROB = 0.0
# -----------------------

_C.GDRNET = CN()
_C.GDRNET.BETA = 0.5
_C.GDRNET.TEMPERATURE = 0.1
_C.GDRNET.SCALING_FACTOR = 4.

_C.FISHR = CN()
_C.FISHR.NUM_GROUPS = 0
_C.FISHR.EMA = 0.
_C.FISHR.PENALTY_ANNEAL_ITERS = 0
_C.FISHR.LAMBDA = 0.

_C.DRGEN = CN()
_C.DRGEN.N_CONVERGENCE = 0
_C.DRGEN.N_TOLERANCE = 0
_C.DRGEN.TOLERANCE_RATIO = 0.